// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// /// Errors generated by the X server.
// pub mod error;

pub mod event;

// Requests: commands to the X server.
//
// Requests are messages sent _from_ the client _to_ the X server. They are
// commands for the X server to carry out. Some requests generate replies
// that are sent back to the client.
// pub mod request;
